"use client";

import type { ReactNode } from "react";
import Link from "next/link";
import { useLanguage } from "@/components/i18n/LanguageProvider";
import visualStyles from "./WhatWeDoVisuals.module.css";

type Service = { number: string; title: string; description: string; note: string; visual: "website" | "software" | "automation" | "systems" };
type Copy = { heading: ReactNode; intro: string; learnMore: string; footer: string; portfolioPrompt: string; exploreWork: string; services: Service[] };

const content: Record<"en" | "es", Copy> = {
  en: { heading: <>Digital solutions<br />to help grow<br />your business.</>, intro: "We design, build and automate digital tools that let you focus on what matters most: growing your business.", learnMore: "LEARN MORE", footer: "SAME PURPOSE. DIFFERENT PATHS.", portfolioPrompt: "This is what happens when ideas become real digital solutions.", exploreWork: "EXPLORE OUR WORK", services: [
    { number: "01", title: "Websites", description: "We design clear, professional websites that represent your business and make it easier to attract new clients.", note: "Ideal for businesses that need an online presence or want to improve how they present their services.", visual: "website" },
    { number: "02", title: "Custom Software", description: "We build systems tailored to the way your business works. Organize tasks, processes and operations in a tool designed for your day-to-day needs.", note: "Built for businesses that can no longer manage their operations with generic tools or manual processes.", visual: "software" },
    { number: "03", title: "Automation & AI", description: "We automate repetitive tasks and connect your tools to reduce manual work. Less time operating, more time focused on growing your business.", note: "Especially useful if you spend a large part of your day answering, managing or repeating manual tasks.", visual: "automation" },
    { number: "04", title: "Connected Systems", description: "We connect the different parts of your digital business so information, tools and processes work together as one system.", note: "For businesses that need more than individual solutions and want their digital infrastructure to work together.", visual: "systems" },
  ] },
  es: { heading: <>Soluciones digitales<br />para hacer crecer<br />tu negocio.</>, intro: "Diseñamos, desarrollamos y automatizamos herramientas digitales para que puedas enfocarte en lo más importante: hacer crecer tu negocio.", learnMore: "SABER MÁS", footer: "MISMO PROPÓSITO. DIFERENTES CAMINOS.", portfolioPrompt: "Esto es lo que ocurre cuando las ideas se convierten en soluciones digitales reales.", exploreWork: "EXPLORA NUESTRO TRABAJO", services: [
    { number: "01", title: "Páginas Web", description: "Diseñamos páginas web claras y profesionales que representan tu negocio y facilitan la captación de clientes.", note: "Ideal para negocios que necesitan presencia online o mejorar cómo presentan sus servicios.", visual: "website" },
    { number: "02", title: "Software a Medida", description: "Creamos sistemas adaptados a cómo funciona tu negocio. Organiza tareas, procesos y operaciones en una herramienta pensada para tu día a día.", note: "Pensado para negocios que ya no pueden manejar su operación con herramientas genéricas o procesos manuales.", visual: "software" },
    { number: "03", title: "Automatización e IA", description: "Automatizamos tareas repetitivas y conectamos tus herramientas para reducir trabajo manual. Menos tiempo operando, más tiempo enfocándote en hacer crecer tu negocio.", note: "Especialmente útil si pasas gran parte del día respondiendo, gestionando o repitiendo tareas manualmente.", visual: "automation" },
    { number: "04", title: "Sistemas Conectados", description: "Conectamos las diferentes partes de tu negocio digital para que la información, las herramientas y los procesos funcionen como un solo sistema.", note: "Para negocios que necesitan más que soluciones individuales y quieren que toda su infraestructura digital trabaje en conjunto.", visual: "systems" },
  ] },
};

function ServiceVisual({ type, language }: { type: Service["visual"]; language: "en" | "es" }) {
  const es = language === "es";
  if (type === "website") return <div className={`${visualStyles.visual} ${visualStyles.website}`} aria-hidden="true" data-parallax><div className={visualStyles.websiteFrame}><div className={visualStyles.websiteTop}><strong>NORD / STUDIO</strong><div><span>{es ? "PROYECTOS" : "PROJECTS"}</span><span>{es ? "SOBRE NOSOTROS" : "ABOUT"}</span><span>{es ? "CONTACTO" : "CONTACT"}</span></div></div><div className={visualStyles.websiteImage}><div className={visualStyles.websiteOverlay}><p>{es ? "ARQUITECTURA · INTERIORES" : "ARCHITECTURE · INTERIORS"}</p><h4>{es ? <>Espacios<br />con intención.</> : <>Creating spaces<br />with intention.</>}</h4><button>{es ? "VER PROYECTOS" : "VIEW PROJECTS"} <b>→</b></button></div></div><div className={visualStyles.websiteFooter}><span>{es ? "COPENHAGUE — DINAMARCA" : "COPENHAGEN — DENMARK"}</span><span>SCROLL TO EXPLORE ↓</span></div></div></div>;
  if (type === "software") return <div className={`${visualStyles.visual} ${visualStyles.software}`} aria-hidden="true" data-parallax><div className={visualStyles.dashboard}><aside className={visualStyles.dashboardSidebar}><strong>FIELDWORK</strong><span className={visualStyles.selected}>{es ? "Resumen" : "Overview"}</span><span>{es ? "Proyectos" : "Projects"}</span><span>{es ? "Calendario" : "Calendar"}</span><span>{es ? "Clientes" : "Clients"}</span><span>{es ? "Equipo" : "Team"}</span><small>© 2026</small></aside><main className={visualStyles.dashboardMain}><header><div><p>{es ? "OPERACIONES" : "OPERATIONS"}</p><h4>{es ? "Todos los proyectos." : "Everything in motion."}</h4></div><span className={visualStyles.dashboardDate}>SEP 09, 2026</span></header><section className={visualStyles.projectBoard}><div className={visualStyles.boardHead}><span>{es ? "PROYECTOS ACTIVOS" : "ACTIVE PROJECTS"}</span><button>+ {es ? "NUEVO" : "NEW"}</button></div><div className={visualStyles.projectColumns}><div><small>PLANNING <b>04</b></small><article><strong>Nord Office</strong><span>Concept review</span><i /></article><article><strong>Harbour House</strong><span>Materials</span><i /></article></div><div><small>IN PROGRESS <b>06</b></small><article><strong>Østerbro</strong><span>Client review</span><i /></article><article><strong>Studio 04</strong><span>Production</span><i /></article></div><div><small>COMPLETED <b>12</b></small><article><strong>Green Room</strong><span>Delivered</span><i /></article></div></div></section><section className={visualStyles.dashboardBottom}><div><small>{es ? "HOY" : "TODAY"}</small><p><b>09:30</b> Client meeting — Nord Office</p><p><b>12:00</b> Team review — Studio 04</p></div><div><small>{es ? "ACTIVIDAD RECIENTE" : "RECENT ACTIVITY"}</small><p>Anna uploaded new documents</p><p>Client approved proposal</p></div></section></main></div></div>;
  if (type === "automation") return <div className={`${visualStyles.visual} ${visualStyles.automation}`} aria-hidden="true" data-parallax><div className={visualStyles.automationCanvas}><div className={visualStyles.canvasTop}><span>AUTOMATIONS</span><b>LIVE</b></div><div className={visualStyles.canvas}><div className={`${visualStyles.node} ${visualStyles.triggerNode}`}><small>{es ? "DISPARADOR" : "TRIGGER"}</small><strong>{es ? "Nueva solicitud" : "New request"}</strong><span>Website form</span></div><div className={visualStyles.connectorOne} /><div className={visualStyles.connectorTwo} /><div className={`${visualStyles.node} ${visualStyles.actionOne}`}><small>ACTION 01</small><strong>{es ? "Crear cliente" : "Create client"}</strong><span>CRM</span></div><div className={`${visualStyles.node} ${visualStyles.actionTwo}`}><small>ACTION 02</small><strong>{es ? "Crear proyecto" : "Create project"}</strong><span>Workspace</span></div><div className={`${visualStyles.node} ${visualStyles.actionThree}`}><small>ACTION 03</small><strong>{es ? "Avisar al equipo" : "Notify team"}</strong><span>Slack</span></div><div className={`${visualStyles.node} ${visualStyles.actionFour}`}><small>ACTION 04</small><strong>{es ? "Programar seguimiento" : "Schedule follow-up"}</strong><span>Calendar</span></div><div className={visualStyles.connectionVertical} /><div className={visualStyles.connectionBottom} /></div><div className={visualStyles.canvasLegend}><span><i /> {es ? "Proceso activo" : "Active process"}</span><span>{es ? "1 evento → 4 acciones" : "1 event → 4 actions"}</span></div></div></div>;
  return <div className={`${visualStyles.visual} ${visualStyles.systems}`} aria-hidden="true" data-parallax><div className={visualStyles.systemMap}><div className={visualStyles.systemLabel}>{es ? "ECOSISTEMA DIGITAL" : "DIGITAL ECOSYSTEM"}</div><div className={`${visualStyles.systemCard} ${visualStyles.systemWebsite}`}><small>01 / WEBSITE</small><strong>ONLINE<br />PRESENCE</strong><span>{es ? "Tu negocio online" : "Your business online"}</span></div><div className={`${visualStyles.systemCard} ${visualStyles.systemDashboard}`}><small>02 / SOFTWARE</small><strong>YOUR<br />OPERATIONS</strong><span>{es ? "Tu operación centralizada" : "Your operations centralized"}</span></div><div className={`${visualStyles.systemCard} ${visualStyles.systemAutomation}`}><small>03 / AUTOMATION</small><strong>WORKING<br />AUTOMATICALLY</strong><span>{es ? "Procesos conectados" : "Connected processes"}</span></div><div className={visualStyles.systemLineOne} /><div className={visualStyles.systemLineTwo} /><div className={visualStyles.systemLineThree} /><div className={visualStyles.systemCore}><span>LEBA</span><strong>{es ? "TODO<br />CONECTADO" : "EVERYTHING<br />CONNECTED"}</strong></div><div className={visualStyles.systemStatus}><i /> {es ? "TODOS LOS SISTEMAS CONECTADOS" : "ALL SYSTEMS CONNECTED"}</div></div></div>;
}

export function WhatWeDo() {
  const { language } = useLanguage();
  const copy = content[language] || content.en;
  return <section className={`what-we-do language-${language}`} id="what-we-do"><div className="what-we-do-inner"><div className="what-we-do-intro"><div className="section-kicker" data-reveal="left"><span /> WHAT WE DO</div><h2 data-reveal>{copy.heading}</h2><p className="motion-stagger-1" data-reveal="right">{copy.intro}</p></div><div className="service-grid">{copy.services.map((service, index) => <article className={`service-card motion-stagger-${index + 1}`} data-reveal="scale" key={service.number}><div className="service-topline"><span>{service.number}</span><i /></div><ServiceVisual type={service.visual} language={language} /><h3>{service.title}</h3><p className="service-description">{service.description}</p><p className="service-note">{service.note}</p><a className="service-link focusable" href="#contact">{copy.learnMore} <span /></a></article>)}</div><div className="what-we-do-footer" data-reveal><div><span><i /> {copy.footer}</span><p className="what-we-do-portfolio-prompt">{copy.portfolioPrompt}</p></div><Link className="what-we-do-work-link focusable" href="/work">{copy.exploreWork} <b>⟶</b></Link></div></div></section>;
}
