"use client";

import type { CSSProperties, ReactNode } from "react";
import Link from "next/link";
import { useLanguage } from "@/components/i18n/LanguageProvider";

type Service = { number: string; title: string; description: string; note: string; visual: "website" | "software" | "automation" };
type Copy = { heading: ReactNode; intro: string; learnMore: string; footer: string; portfolioPrompt: string; exploreWork: string; services: Service[] };

const content: Record<"en" | "es", Copy> = {
  en: { heading: <>Digital solutions<br />to help grow<br />your business.</>, intro: "We design, build and automate digital tools that let you focus on what matters most: growing your business.", learnMore: "LEARN MORE", footer: "SAME PURPOSE. DIFFERENT PATHS.", portfolioPrompt: "This is what happens when ideas become real digital solutions.", exploreWork: "EXPLORE OUR WORK", services: [
    { number: "01", title: "Websites", description: "We design clear, professional websites that represent your business and make it easier to attract new clients.", note: "Ideal for businesses that need an online presence or want to improve how they present their services.", visual: "website" },
    { number: "02", title: "Custom Software", description: "We build systems tailored to the way your business works. Organize tasks, processes and operations in a tool designed for your day-to-day needs.", note: "Built for businesses that can no longer manage their operations with generic tools or manual processes.", visual: "software" },
    { number: "03", title: "Automation & AI", description: "We automate repetitive tasks and connect your tools to reduce manual work. Less time operating, more time focused on growing your business.", note: "Especially useful if you spend a large part of your day answering, managing or repeating manual tasks.", visual: "automation" },
  ] },
  es: { heading: <>Soluciones digitales<br />para hacer crecer<br />tu negocio.</>, intro: "Diseñamos, desarrollamos y automatizamos herramientas digitales para que puedas enfocarte en lo más importante: hacer crecer tu negocio.", learnMore: "SABER MÁS", footer: "MISMO PROPÓSITO. DIFERENTES CAMINOS.", portfolioPrompt: "Esto es lo que ocurre cuando las ideas se convierten en soluciones digitales reales.", exploreWork: "EXPLORA NUESTRO TRABAJO", services: [
    { number: "01", title: "Páginas Web", description: "Diseñamos páginas web claras y profesionales que representan tu negocio y facilitan la captación de clientes.", note: "Ideal para negocios que necesitan presencia online o mejorar cómo presentan sus servicios.", visual: "website" },
    { number: "02", title: "Software a Medida", description: "Creamos sistemas adaptados a cómo funciona tu negocio. Organiza tareas, procesos y operaciones en una herramienta pensada para tu día a día.", note: "Pensado para negocios que ya no pueden manejar su operación con herramientas genéricas o procesos manuales.", visual: "software" },
    { number: "03", title: "Automatización e IA", description: "Automatizamos tareas repetitivas y conectamos tus herramientas para reducir trabajo manual. Menos tiempo operando, más tiempo enfocándote en hacer crecer tu negocio.", note: "Especialmente útil si pasas gran parte del día respondiendo, gestionando o repitiendo tareas manualmente.", visual: "automation" },
  ] },
};

function ServiceVisual({ type, language }: { type: Service["visual"]; language: "en" | "es" }) {
  const isSpanish = language === "es";
  const motion = { website: ".18", software: ".12", automation: ".16" }[type];
  const style = { "--parallax-speed": motion } as CSSProperties;
  if (type === "website") return <div className="service-visual service-visual-website" aria-hidden="true" data-parallax style={style}><div className="visual-laptop"><div className="visual-laptop-screen"><div className="visual-browser-bar"><span /><span /><span /></div><div className="visual-website-copy"><small>WE ARE LEBA</small><strong>{isSpanish ? <>Tu negocio,<br />en su mejor versión.</> : <>Your business,<br />at its best.</>}</strong><i /></div><div className="visual-website-orb" /></div><div className="visual-laptop-base" /></div></div>;
  if (type === "software") return <div className="service-visual service-visual-software" aria-hidden="true" data-parallax style={style}><div className="visual-dashboard"><aside><b>{isSpanish ? "Tu Negocio" : "Your Business"}</b><span>{isSpanish ? "Inicio" : "Home"}</span><span>{isSpanish ? "Clientes" : "Clients"}</span><span>{isSpanish ? "Servicios" : "Services"}</span><span>{isSpanish ? "Reservas" : "Bookings"}</span><span>{isSpanish ? "Reportes" : "Reports"}</span></aside><div className="visual-dashboard-main"><div className="visual-dashboard-title">{isSpanish ? "Resumen" : "Overview"}</div><div className="visual-stat-grid"><div><small>{isSpanish ? "Clientes" : "Clients"}</small><b>124</b><em>↗ 12%</em></div><div><small>{isSpanish ? "Reservas" : "Bookings"}</small><b>58</b><em>↗ 8%</em></div></div><div className="visual-list-title">{isSpanish ? "Próximas reservas" : "Upcoming bookings"}</div><div className="visual-list-row"><i /> <span>Maria Gonzalez</span><small>10:00</small></div><div className="visual-list-row"><i /> <span>Juan Perez</span><small>11:30</small></div></div></div></div>;
  return <div className="service-visual service-visual-automation" aria-hidden="true" data-parallax style={style}><div className="automation-flow"><div className="automation-inputs"><div>↗ <span>{isSpanish ? "Nuevos mensajes" : "New messages"}</span></div><div>▣ <span>{isSpanish ? "Nuevas reservas" : "New bookings"}</span></div><div>✉ <span>{isSpanish ? "Formularios" : "Forms"}</span></div><div>≋ <span>{isSpanish ? "Otras herramientas" : "Other tools"}</span></div></div><div className="automation-core">✦<small>{isSpanish ? "Automatizar" : "Automate"}</small></div><div className="automation-output"><span>✓ &nbsp; {isSpanish ? "Responder" : "Reply"}</span><span>✓ &nbsp; {isSpanish ? "Crear tarea" : "Create task"}</span><span>✓ &nbsp; {isSpanish ? "Actualizar cliente" : "Update client"}</span><span>✓ &nbsp; {isSpanish ? "Enviar notificación" : "Send notification"}</span></div></div></div>;
}

export function WhatWeDo() {
  const { language } = useLanguage();
  const copy = content[language] || content.en;
  return <section className={`what-we-do language-${language}`} id="what-we-do"><div className="what-we-do-inner"><div className="what-we-do-intro"><div className="section-kicker" data-reveal="left"><span /> WHAT WE DO</div><h2 data-reveal>{copy.heading}</h2><p className="motion-stagger-1" data-reveal="right">{copy.intro}</p></div><div className="service-grid">{copy.services.map((service, index) => <article className={`service-card motion-stagger-${index + 1}`} data-reveal="scale" key={service.number}><div className="service-topline"><span>{service.number}</span><i /></div><ServiceVisual type={service.visual} language={language} /><h3>{service.title}</h3><p className="service-description">{service.description}</p><p className="service-note">{service.note}</p><a className="service-link focusable" href="#contact">{copy.learnMore} <span /></a></article>)}</div><div className="what-we-do-footer" data-reveal><div><span><i /> {copy.footer}</span><p className="what-we-do-portfolio-prompt">{copy.portfolioPrompt}</p></div><Link className="what-we-do-work-link focusable" href="/work">{copy.exploreWork} <b>⟶</b></Link></div></div></section>;
}
